<?php
/**
 * Structured knowledge base extracted from the Norzagaray Citizen's Charter
 * (2025, 1st Edition) — used by user/chatbot-api.php to answer citizens'
 * questions about document/service requirements, fees, and processing time.
 *
 * Each entry: office, title, keywords (phrases to match against a citizen's
 * message), requirements (checklist), fee, processing_time.
 *
 * Source figures (fees/timelines) reflect the published charter and may
 * change — the chatbot reply always tells the citizen to confirm at the
 * counter.
 */

return [
    // ---------- Business Permits & Licensing Office (BPLO) ----------
    [
        'office' => "Business Permits & Licensing Office",
        'title' => "Issuance of Business Permit (New)",
        'keywords' => ["new business permit", "business permit", "mayor's permit", "mayors permit", "mayor's clearance", "mayors clearance", "start a business", "register a business", "open a business"],
        'requirements' => [
            "Community Tax Certificate / CTC (Municipal Treasurer's Office)",
            "Barangay Business Clearance for the current year",
            "Proof of registration: DTI (sole proprietorship), SEC (partnership/corporation), or CDA (cooperative)",
            "Proof of right to use the property as business location (TCT/Tax Declaration if owned; notarized Lease Contract or Affidavit to Use if not)",
            "Certificate of Non-Coverage (CNC) and clearances from MENRO, MPDO (zoning), Engineering (occupancy), Rural Health Office (sanitary), and BFP (fire safety) as applicable",
            "Special document requirements for regulated businesses (e.g. FDA license for pharmacies, DOLE/POEA for agencies) — ask BPLO if yours applies",
        ],
        'fee' => "Varies by clearance — e.g. CNC around ₱1,000, plus MPDO/BFP assessment based on your business",
        'processing_time' => "About 1 day and 45 minutes once all requirements are complete",
    ],
    [
        'office' => "Business Permits & Licensing Office",
        'title' => "Renewal of Business Permit",
        'keywords' => ["renew business permit", "business permit renewal", "renewal of business permit"],
        'requirements' => [
            "Community Tax Certificate / CTC",
            "Barangay Business Clearance for the current year",
            "Proof of registration (DTI/SEC/CDA)",
            "Previous year's Mayor's Permit",
            "Proof of tax payments (BIR) or notarized Affidavit of Declaration of Gross Income",
            "Certificate of tax exemption, if your business is tax-exempt",
        ],
        'fee' => "Based on assessed gross sales/receipts",
        'processing_time' => "About 1 day and 45 minutes",
    ],
    [
        'office' => "Business Permits & Licensing Office",
        'title' => "Motorized Tricycle Operator's Permit (MTOP)",
        'keywords' => ["tricycle permit", "mtop", "motorized tricycle"],
        'requirements' => [
            "Barangay Clearance for the current year",
            "Police Clearance",
            "Certification from the TODA President and the Federation President",
            "Official Receipt (OR) and Certificate of Registration (CR) of the tricycle",
            "Professional Driver's License",
            "Deed of Sale / Sales Invoice",
            "Voter's ID or Certified True Copy of Voter Registration (VRR)",
        ],
        'fee' => "₱575 for new, ₱210 for renewal",
        'processing_time' => "About 1 day and 30 minutes",
    ],

    // ---------- Municipal Assessor's Office ----------
    [
        'office' => "Municipal Assessor's Office",
        'title' => "Transfer of Tax Declaration to New Owner/s",
        'keywords' => ["transfer tax declaration", "transfer of ownership property", "change owner tax declaration"],
        'requirements' => [
            "New title (if titled) or Deed of Conveyance (Sale, Donation, or Extrajudicial Settlement)",
            "BIR Certification (Capital Gains Tax, Donor's Tax, or Estate Tax)",
            "Transfer Tax receipt (Provincial Treasurer's Office)",
            "Latest/updated Real Property Tax Receipt",
            "If applicable: subdivision/consolidation plan, Affidavit of Publication (inherited property), DAR clearance, SPA if represented by someone else",
        ],
        'fee' => "₱200 per Tax Declaration",
        'processing_time' => "About 1 hour",
    ],
    [
        'office' => "Municipal Assessor's Office",
        'title' => "Consolidation and Subdivision of Property",
        'keywords' => ["consolidation of property", "subdivision of land", "subdivide property", "merge lots", "merge parcels"],
        'requirements' => [
            "Title/s (if titled)",
            "Approved subdivision/consolidation plan (Bureau of Lands)",
            "Latest/updated Real Property Tax Receipt",
        ],
        'fee' => "₱200 per Tax Declaration",
        'processing_time' => "About 1 hour",
    ],
    [
        'office' => "Municipal Assessor's Office",
        'title' => "Demolition and Cancellation of Property Record",
        'keywords' => ["demolition of property", "cancel tax declaration", "cancellation of property record"],
        'requirements' => [
            "Written request",
            "Latest/updated Real Property Tax Receipt",
            "Ocular inspection report (conducted by the Assessor's Office)",
            "Demolition Permit (Engineering Office) and/or Certification of Business Closure (BPLO), if applicable",
        ],
        'fee' => "None",
        'processing_time' => "About 2 hours 31 minutes (includes the ocular inspection)",
    ],
    [
        'office' => "Municipal Assessor's Office",
        'title' => "Reassessment / Assessment of Property",
        'keywords' => ["reassessment of property", "assess new property", "declare new property for tax"],
        'requirements' => [
            "Written request",
            "Latest/updated Real Property Tax Receipt",
            "Ocular inspection report",
        ],
        'fee' => "₱200 per Tax Declaration",
        'processing_time' => "About 2 hours 56 minutes (includes ocular inspection, 2–8 hours depending on location)",
    ],
    [
        'office' => "Municipal Assessor's Office",
        'title' => "Reclassification of Property",
        'keywords' => ["reclassification of property", "reclassify land"],
        'requirements' => [
            "Title/s",
            "Sangguniang Bayan Resolution",
            "Sangguniang Panlalawigan Resolution",
            "Latest/updated Real Property Tax Receipt",
        ],
        'fee' => "₱200 per Tax Declaration",
        'processing_time' => "About 1 hour",
    ],
    [
        'office' => "Municipal Assessor's Office",
        'title' => "Tax Declaration for Newly Assessed Land, Building, or Machinery",
        'keywords' => ["new tax declaration", "tax declaration for new building", "newly assessed property", "declare new machinery"],
        'requirements' => [
            "For land: existing Tax Declaration",
            "For a building: Building Permit, Architectural Plan, Cost Estimate, Certificate of Occupancy",
            "For machinery: Notarized Sworn Statement, plus SPA if represented",
        ],
        'fee' => "₱200 per Tax Declaration",
        'processing_time' => "About 2 hours 56 minutes",
    ],
    [
        'office' => "Municipal Assessor's Office",
        'title' => "Certified True Copy of Tax Declaration",
        'keywords' => ["certified true copy of tax declaration", "copy of tax declaration"],
        'requirements' => [
            "Copy of Tax Declaration",
            "Latest/updated Real Property Tax Receipt",
            "Letter request from the owner or authorized representative (with SPA if represented)",
        ],
        'fee' => "₱100 per Tax Declaration",
        'processing_time' => "About 25 minutes",
    ],
    [
        'office' => "Municipal Assessor's Office",
        'title' => "Property Certifications (With/Without Improvement, Land Holdings, No Property)",
        'keywords' => ["certificate of no property", "certificate of land holdings", "certificate with improvement", "certificate non improvement", "indigency property certificate"],
        'requirements' => [
            "Copy of Tax Declaration",
            "Latest/updated Real Property Tax Receipt",
            "Letter request from the owner or authorized representative (with SPA if represented)",
        ],
        'fee' => "₱100 per certification",
        'processing_time' => "About 25 minutes",
    ],

    // ---------- Municipal Civil Registrar's Office (MCRO) ----------
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "Certified True Copy of Birth / Death / Marriage Certificate",
        'keywords' => ["certified true copy of birth certificate", "copy of birth certificate", "copy of death certificate", "copy of marriage certificate", "form 1a", "form 2a", "form 3a"],
        'requirements' => [
            "Accomplished request slip",
            "1 photocopy of 2 valid IDs",
            "If through a representative: original authorization letter or SPA, plus valid ID of both the owner and the representative",
        ],
        'fee' => "About ₱200 total (verification fee + copy fee)",
        'processing_time' => "About 12 minutes",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "Registration of Birth, Death, or Marriage",
        'keywords' => ["register a birth", "register a death", "register a marriage", "birth registration", "death registration", "marriage registration"],
        'requirements' => [
            "Duly accomplished Certificate of Live Birth/Death/Marriage (4 original copies, from the hospital/officiant)",
            "Residence Certificate (Cedula) of parents, if not married",
            "Valid ID of the informant",
            "Marriage Certificate of parents, if applicable",
            "Affidavit of Paternity and Affidavit to Use the Surname of the Father, if not married",
        ],
        'fee' => "About ₱650 total (birth ₱100, marriage ₱100, burial ₱50, misc ₱100, cadaver transfer ₱200 — as applicable)",
        'processing_time' => "About 36 minutes",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "Application for Marriage License",
        'keywords' => ["marriage license", "apply for marriage license"],
        'requirements' => [
            "PSA CENOMAR (original)",
            "Birth Certificate",
            "Residence Certificate (Cedula)",
            "If 18–20 years old: parental consent signed by the father at MCRO, plus the father's valid ID and Cedula",
        ],
        'fee' => "About ₱400 total",
        'processing_time' => "About 36 minutes to process, but the license can only be released after a mandatory 10-calendar-day posting period",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "Late Registration / Out-of-Town Registration of Birth, Death, or Marriage",
        'keywords' => ["late registration of birth", "delayed registration", "out of town registration"],
        'requirements' => [
            "4 copies of duly accomplished Certificate of Live Birth (or the Death/Marriage equivalent)",
            "Affidavit of Delayed Registration",
            "Negative Certification from PSA",
            "Two documentary evidence plus Affidavit of Two Disinterested Persons",
            "National ID of the registrant and parents, Barangay Certification of residency, 2 recent photos",
            "Additional affidavits depending on your case (paternity, whereabouts of mother, etc.)",
        ],
        'fee' => "₱150",
        'processing_time' => "About 21 minutes to process, then a required 10-calendar-day posting period before release",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "Supplemental Report (correcting an omitted entry)",
        'keywords' => ["supplemental report birth certificate", "missing entry birth certificate"],
        'requirements' => [
            "PSA Birth Certificate and local copy",
            "Affidavit of Supplemental Report (valid for 1 month)",
            "Baptismal Certificate, School Record, 2 valid IDs",
            "Birth/Marriage Certificates of parents",
        ],
        'fee' => "₱150",
        'processing_time' => "About 1 month (the annotated copy is released by PSA after 1 month)",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "RA 9255 — Affidavit to Use the Surname of the Father (AUSF)",
        'keywords' => ["use surname of father", "ra 9255", "ausf"],
        'requirements' => [
            "Affidavit of Acknowledgment/Admission of Paternity",
            "Birth Certificate of the child",
            "AUSF form (with the mother's sworn attestation if the child is 7–20 years old)",
            "Valid IDs of parents and child",
        ],
        'fee' => "₱150",
        'processing_time' => "About 1 month (annotated document released by PSA)",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "Legitimation",
        'keywords' => ["legitimation of child", "legitimate a child", "legitimation"],
        'requirements' => [
            "Affidavit of Legitimation",
            "Birth Certificate of the child (PSA and local copy)",
            "Marriage Certificate of parents, Baptismal Certificate",
            "PSA Advisory on Marriage (both parents), valid IDs",
        ],
        'fee' => "₱150",
        'processing_time' => "About 1 month",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "Petition for Correction — RA 10172 (Gender / Date / Month of Birth)",
        'keywords' => ["ra 10172", "correct gender", "correct date of birth", "correct month of birth"],
        'requirements' => [
            "PSA and local copy of the Birth/Death/Marriage Certificate",
            "Baptismal Certificate, Medical Record/Certificate",
            "NBI and Police Clearance, Affidavit of Employment/Non-Employment",
            "Form 137/Transcript, Cedula, Voter's Certification, 2 valid IDs",
            "Newspaper publication (you shoulder roughly ₱1,500 publisher fee)",
            "Full checklist can vary by case — MCRO will confirm exactly what applies to you",
        ],
        'fee' => "₱3,000 plus about ₱1,500 for required newspaper publication",
        'processing_time' => "About 4 months (includes mandatory 10-day posting and PSA review)",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "RA 9048 — Correction of Clerical Error",
        'keywords' => ["ra 9048", "clerical error correction", "misspelled name correction"],
        'requirements' => [
            "PSA and local copy of the Birth/Death/Marriage Certificate",
            "Baptismal Certificate, Marriage Contract",
            "Birth Certificates of siblings/children, Cedula, Voter's Registration, 2 valid IDs",
            "Full checklist can vary by case — MCRO will confirm exactly what applies to you",
        ],
        'fee' => "₱1,000",
        'processing_time' => "About 50 days (includes posting and PSA review)",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "RA 9048 — Petition for Change of First Name",
        'keywords' => ["change of first name", "petition for change of name"],
        'requirements' => [
            "PSA and local copy of Birth Certificate, Baptismal Certificate",
            "Marriage Contract, NBI and Police Clearance",
            "Affidavit of Employment/Non-Employment, Form 137/Diploma, Cedula",
            "Newspaper publication, Voter's Certification, 2 valid IDs",
        ],
        'fee' => "₱3,000 plus about ₱1,500 for required newspaper publication",
        'processing_time' => "About 4 months",
    ],
    [
        'office' => "Municipal Civil Registrar's Office",
        'title' => "Endorsement of Negative Certification / Clear Copy / Advance Copy",
        'keywords' => ["negative certification", "advance copy of birth certificate", "clear copy endorsement"],
        'requirements' => [
            "PSA Negative Certification",
            "Proof of urgency, 1 valid ID",
            "Certificate of Live Birth (Municipal Form)",
        ],
        'fee' => "₱100–150",
        'processing_time' => "About 31 days",
    ],

    // ---------- Municipal Engineering Office ----------
    [
        'office' => "Municipal Engineering Office",
        'title' => "Building Permit",
        'keywords' => ["building permit", "construct a building", "construction permit"],
        'requirements' => [
            "Barangay Clearance for Building Permit",
            "Proof of Lot Ownership",
            "Locational/Zoning Clearance (MPDO)",
            "Fire Safety Evaluation Clearance (BFP)",
            "Construction Safety & Health Program (DOLE)",
            "5 sets of survey plans, design plans, and related documents",
            "Clearances from other agencies if needed (DPWH, DepEd, CAAP, DENR, DOH, etc.)",
            "Apply online: bldg.ibpls.com/norzagaraybulacan",
        ],
        'fee' => "Based on the National Building Code fee schedule and local ordinances",
        'processing_time' => "About 1 day and 1 hour 22 minutes",
    ],
    [
        'office' => "Municipal Engineering Office",
        'title' => "Certificate of Occupancy",
        'keywords' => ["certificate of occupancy", "occupancy certificate", "occupancy permit"],
        'requirements' => [
            "Issued Building Permit and Fire Safety/Locational Clearance",
            "3 notarized copies of Certificate of Completion",
            "As-Built Plan and Construction Logbook (signed & sealed)",
            "Captioned site photos of the completed building",
            "Yellow card from your electrical source provider (e.g. Meralco)",
            "Apply online: co.ibpls.com/norzagaraybulacan",
        ],
        'fee' => "Based on the National Building Code fee schedule",
        'processing_time' => "About 1 day and 53 minutes",
    ],
    [
        'office' => "Municipal Engineering Office",
        'title' => "Certificate of Electrical Inspection and Wiring Permit",
        'keywords' => ["electrical inspection", "wiring permit"],
        'requirements' => [
            "Proof of lot ownership, Barangay Clearance for Electrical/Wiring",
            "Issued Building Permit, 2 valid IDs",
            "Wiring Permit signed by a licensed professional or registered electrical engineer",
        ],
        'fee' => "Based on the National Building Code fee schedule",
        'processing_time' => "About 2 hours 30 minutes (includes ocular inspection)",
    ],

    // ---------- Municipal Health Office (MHO) ----------
    [
        'office' => "Municipal Health Office",
        'title' => "Medical Consultation",
        'keywords' => ["medical consultation", "see a doctor", "checkup at health center"],
        'requirements' => ["Your physical presence", "Previous medical record related to your condition, if you have one"],
        'fee' => "Free",
        'processing_time' => "About 20–40 minutes, depending on whether lab tests are needed",
    ],
    [
        'office' => "Municipal Health Office",
        'title' => "Dental Consultation",
        'keywords' => ["dental consultation", "tooth extraction", "see a dentist"],
        'requirements' => ["Your physical presence", "Previous dental record, if applicable"],
        'fee' => "Free",
        'processing_time' => "About 65 minutes",
    ],
    [
        'office' => "Municipal Health Office",
        'title' => "Maternal Health Care Services",
        'keywords' => ["maternal health", "prenatal checkup", "pregnancy checkup"],
        'requirements' => ["Your physical presence", "Maternal & child booklet, if you have one"],
        'fee' => "Free",
        'processing_time' => "About 35 minutes",
    ],
    [
        'office' => "Municipal Health Office",
        'title' => "National Immunization Program",
        'keywords' => ["immunization", "vaccination", "vaccine schedule"],
        'requirements' => ["Your physical presence", "Previous vaccination record, if applicable"],
        'fee' => "Free",
        'processing_time' => "About 20 minutes",
    ],
    [
        'office' => "Municipal Health Office",
        'title' => "Family Planning Services",
        'keywords' => ["family planning"],
        'requirements' => ["Your physical presence", "Previous record, if applicable"],
        'fee' => "Free",
        'processing_time' => "About 20 minutes",
    ],
    [
        'office' => "Municipal Health Office",
        'title' => "Processing/Issuance of Death Certificate & Exhumation Permit",
        'keywords' => ["exhumation permit", "process death certificate"],
        'requirements' => ["Filled-out Death Certificate", "Official medical records (from within 10 years before death)", "Original copy of death certificate, for exhumation"],
        'fee' => "₱200",
        'processing_time' => "About 10 minutes",
    ],
    [
        'office' => "Municipal Health Office",
        'title' => "Health Card for Employment",
        'keywords' => ["health card", "health card for employment"],
        'requirements' => ["Medical laboratory result (from a diagnostic laboratory, clinic, or hospital)"],
        'fee' => "₱100",
        'processing_time' => "About 15 minutes",
    ],
    [
        'office' => "Municipal Health Office",
        'title' => "Sanitary Permit",
        'keywords' => ["sanitary permit"],
        'requirements' => ["ECC / Discharge Permit / Permit to Operate as applicable", "Application Permit", "Medical results of employees, if necessary", "Water Test Results, for water refilling stations"],
        'fee' => "₱300–₱2,550 depending on the business and whether inspection is needed",
        'processing_time' => "About 5 minutes for simple cases, up to 1 day if inspection is required",
    ],
    [
        'office' => "Municipal Health Office",
        'title' => "Potability Certificate",
        'keywords' => ["potability certificate", "water potability"],
        'requirements' => ["Water Test Results from a DOH-accredited laboratory"],
        'fee' => "₱100",
        'processing_time' => "About 5 minutes",
    ],

    // ---------- Municipal Planning & Development Office (MPDO) ----------
    [
        'office' => "Municipal Planning & Development Office",
        'title' => "Zoning Certification for Business Permit — Non-Critical Projects (New)",
        'keywords' => ["zoning certification business", "zoning clearance business"],
        'requirements' => ["Proof of property ownership/lease", "DTI/SEC/CDA registration", "Updated Barangay Clearance", "Sketch of location, actual project photo", "Certificate of Non-Coverage (CNC)", "Latest tax receipt"],
        'fee' => "₱500 per hectare",
        'processing_time' => "About 33 minutes",
    ],
    [
        'office' => "Municipal Planning & Development Office",
        'title' => "Zoning Certification for Business Permit — Critical Projects (New)",
        'keywords' => ["zoning certification critical project"],
        'requirements' => ["Same as the non-critical checklist, but with an Environmental Compliance Certificate (ECC) instead of a CNC", "A site inspection is also required before approval"],
        'fee' => "₱500 per hectare",
        'processing_time' => "About 53 minutes, plus a site inspection (subject to inspector availability, up to 48 hours)",
    ],
    [
        'office' => "Municipal Planning & Development Office",
        'title' => "Zoning Certification for Renewal of Business Permit",
        'keywords' => ["zoning certification renewal"],
        'requirements' => ["Photocopy of Business Permit", "Updated Barangay Clearance", "Latest tax receipt", "Actual photos"],
        'fee' => "Minimal, assessed on-site",
        'processing_time' => "About 33 minutes",
    ],
    [
        'office' => "Municipal Planning & Development Office",
        'title' => "Zoning Certification (as to Land Use)",
        'keywords' => ["zoning certification land use", "land use certification"],
        'requirements' => ["Transfer Certificate of Title", "Tax Declaration with latest tax receipt", "Sketch of location"],
        'fee' => "₱500 per hectare",
        'processing_time' => "About 29 minutes",
    ],
    [
        'office' => "Municipal Planning & Development Office",
        'title' => "Locational Clearance for Building Permit — Critical Projects",
        'keywords' => ["locational clearance critical project", "locational clearance"],
        'requirements' => ["Transfer Certificate of Title", "DTI/SEC/CDA registration", "Updated Barangay Clearance", "Sketch of location", "Environmental Compliance Certificate (ECC)", "Latest tax receipt", "Architectural/Site Development Plan with bill of materials", "Supporting affidavits as applicable"],
        'fee' => "Based on the Revenue Code and the project's bill of materials",
        'processing_time' => "About 35 minutes, plus a site inspection",
    ],

    // ---------- MENRO ----------
    [
        'office' => "Municipal Environment & Natural Resources Office (MENRO)",
        'title' => "Environmental Clearance for Business Permit — Non-Critical (New)",
        'keywords' => ["environmental clearance non critical", "environmental clearance new business"],
        'requirements' => ["Application form", "Certificate of Non-Coverage (apply online via EMB-DENR)", "Barangay Business Clearance", "DTI/SEC/CDA registration", "Geotagged photo of the project/business", "Valid government ID"],
        'fee' => "Plus environmental inspection and solid waste management fees assessed per project",
        'processing_time' => "About 12 minutes",
    ],
    [
        'office' => "Municipal Environment & Natural Resources Office (MENRO)",
        'title' => "Environmental Clearance for Business Permit — Non-Critical (Renewal)",
        'keywords' => ["environmental clearance renewal"],
        'requirements' => ["Application form", "Local Certificate of Non-Coverage for renewal, plus its Official Receipt", "Barangay Business Clearance", "DTI/SEC/CDA registration"],
        'fee' => "₱1,000",
        'processing_time' => "About 10 minutes",
    ],
    [
        'office' => "Municipal Environment & Natural Resources Office (MENRO)",
        'title' => "Environmental Clearance for Business Permit — Critical Projects/Areas",
        'keywords' => ["environmental clearance critical project", "environmental clearance critical area"],
        'requirements' => ["Environmental Compliance Certificate (ECC)", "Provincial Government Acknowledgement Certificate", "Barangay Business Clearance", "DTI/SEC registration", "Valid ID", "Renewals also need PCO Accreditation, Permit to Operate, and Wastewater Discharge Permit"],
        'fee' => "Plus environmental, solid waste, and pollution hazard fees assessed per project",
        'processing_time' => "About 20 minutes",
    ],
    [
        'office' => "Municipal Environment & Natural Resources Office (MENRO)",
        'title' => "Certificate of No Objection for Tree Cutting Permit",
        'keywords' => ["tree cutting permit", "certificate of no objection tree", "cut down a tree"],
        'requirements' => ["2 request/application letters (addressed to CENRO-DENR and the Municipal Mayor)", "Authenticated land title or proof of ownership", "Sketch map", "Barangay Endorsement (no objection)", "Geotagged photos of the trees", "Valid government ID", "Chainsaw registration (CENRO-DENR)", "DENR clearance that the area is not forestland/protected"],
        'fee' => "₱300 per tree + ₱100 certification fee + ₱1,000 environmental inspection fee",
        'processing_time' => "About 2 days (includes a joint ocular inspection with DENR)",
    ],

    // ---------- MSWDO ----------
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "Assistance to Individuals in Crisis Situation (AICS)",
        'keywords' => ["aics", "financial assistance", "medical assistance", "burial assistance", "educational assistance", "crisis assistance"],
        'requirements' => ["Barangay Certificate of Indigency", "Letter of request addressed to the Municipal Mayor", "Valid IDs of patient/claimant", "Proof of need: hospital bill/medical certificate (medical), Certificate of Registration & Statement of Account (educational), or funeral contract & death certificate (burial)"],
        'fee' => "Free — this is a benefit, not a paid service",
        'processing_time' => "About 14 minutes",
    ],
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "MSWDO Certification (e.g. Guardianship)",
        'keywords' => ["guardianship certification", "mswdo certification"],
        'requirements' => ["Barangay Certificate of Indigency", "For guardianship: birth certificate of children, guardian's valid ID, notarized Affidavit of Guardianship, barangay certification of the minor's circumstances, death certificate of parents (if applicable)"],
        'fee' => "Free",
        'processing_time' => "About 12 minutes",
    ],
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "Social Case Study Report (SCSR)",
        'keywords' => ["social case study report", "scsr"],
        'requirements' => ["Valid ID of client and the family member processing the SCSR", "Case reference (medical protocol, legal protocol, or other supporting document)"],
        'fee' => "Free",
        'processing_time' => "About 10 days (includes a home visit)",
    ],
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "Adoption",
        'keywords' => ["adoption", "adopt a child"],
        'requirements' => ["Notarized Petition for Adoption", "Home Study Report / Case Study Report", "Birth and marriage certificates of PAPs (SECPA copy)", "NBI/police clearance, medical & psychological evaluations", "Child care plan, character references, proof of financial capacity", "Attendance at a pre-adoption seminar"],
        'fee' => "Free",
        'processing_time' => "About 37 days (Home Study Report preparation alone takes about 30 working days)",
    ],
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "Person With Disability (PWD) ID",
        'keywords' => ["pwd id", "disability id", "person with disability id"],
        'requirements' => ["Medical Certificate stating the disability", "Certificate of Residency", "2 pcs 1x1 ID picture"],
        'fee' => "Free",
        'processing_time' => "About 7 minutes",
    ],
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "Solo Parent's ID",
        'keywords' => ["solo parent id", "solo parent"],
        'requirements' => ["Sworn Affidavit", "Birth certificate of minor children", "Certificate of Attendance at the RA 11861 orientation (new applicants)", "2 pcs 1x1 ID picture", "Proof of income"],
        'fee' => "Free",
        'processing_time' => "About 7 days (includes a home visit)",
    ],
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "Senior Citizen's ID",
        'keywords' => ["senior citizen id", "senior citizen"],
        'requirements' => ["Birth Certificate", "Certificate of Residency", "2 pcs 1x1 ID picture"],
        'fee' => "Free",
        'processing_time' => "About 7 minutes",
    ],
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "Livelihood Assistance",
        'keywords' => ["livelihood assistance", "capital assistance", "business capital assistance"],
        'requirements' => ["Barangay Certificate of Indigency", "Application Form", "Letter of request addressed to the Municipal Mayor", "Photocopy of ID", "Photo of yourself with your livelihood project/site", "List of products or materials needed with prices", "Sketch of your house location"],
        'fee' => "Free — this is interest-free capital assistance",
        'processing_time' => "About 7 days (includes a home visit)",
    ],
    [
        'office' => "Municipal Social Welfare & Development Office (MSWDO)",
        'title' => "Provision of Assistive Devices",
        'keywords' => ["assistive device", "wheelchair request", "assistive devices"],
        'requirements' => ["Barangay Certificate of Indigency", "Letter of request addressed to the Municipal Mayor", "Valid IDs of patient/claimant", "Medical Certificate", "Photo of the patient requesting the device"],
        'fee' => "Free",
        'processing_time' => "About 33 minutes",
    ],

    // ---------- Municipal Treasurer's Office ----------
    [
        'office' => "Municipal Treasurer's Office",
        'title' => "Real Property Tax (RPT) Receipt / Payment",
        'keywords' => ["real property tax", "pay amilyar", "rpt payment", "property tax payment"],
        'requirements' => ["Previous RPT Official Receipt, latest Tax Declaration, or Title", "Valid government-issued ID", "For corporations: letter of request plus SPA if represented"],
        'fee' => "1% of assessed value (Basic RPT) + 1% of assessed value (Special Education Fund), plus penalties or less discounts as applicable",
        'processing_time' => "About 15 minutes for individuals; about 1 day 11 minutes for corporations",
    ],
    [
        'office' => "Municipal Treasurer's Office",
        'title' => "Community Tax Certificate (Cedula)",
        'keywords' => ["cedula", "community tax certificate", "ctc"],
        'requirements' => ["Accomplished information slip", "Valid government-issued ID", "Proof of income/current payslip", "For corporations: Business Permit and Income Tax Return"],
        'fee' => "₱5 basic + ₱1 per ₱1,000 of income for individuals (max ₱5,000); ₱500 basic + ₱2 per ₱5,000 of sales/property for corporations (max ₱10,000)",
        'processing_time' => "About 3 minutes",
    ],
    [
        'office' => "Municipal Treasurer's Office",
        'title' => "Tax Clearance",
        'keywords' => ["tax clearance"],
        'requirements' => ["Previous RPT Official Receipt, latest Tax Declaration, or Title", "Valid government-issued ID", "Latest Community Tax Certificate (Cedula)"],
        'fee' => "₱100",
        'processing_time' => "About 15 minutes",
    ],

    // ---------- Norzagaray Municipal Hospital ----------
    [
        'office' => "Norzagaray Municipal Hospital",
        'title' => "Out-Patient Treatment",
        'keywords' => ["hospital outpatient", "hospital consultation", "opd norzagaray"],
        'requirements' => ["Just your personal appearance at the Outpatient Department"],
        'fee' => "Free, or based on the billing statement if medicines/lab tests are needed",
        'processing_time' => "About 20–40 minutes",
    ],
    [
        'office' => "Norzagaray Municipal Hospital",
        'title' => "Emergency Services",
        'keywords' => ["hospital emergency", "emergency room norzagaray"],
        'requirements' => ["Your personal appearance", "One companion/relative"],
        'fee' => "Free, or based on the billing statement",
        'processing_time' => "Case-to-case basis",
    ],
];
